language: php

php:
    - 7.0
    - 7.1
    - 7.2

install:
    - composer install
    - composer database:migrate

script:
    - composer run test:cs
    - composer run test:unit -- --coverage-clover clover-unit.xml
    - composer run test:integration -- --coverage-clover clover-integration.xml
    - composer run test:feature

after_success:
    - composer require --dev satooshi/php-coveralls
    - ./vendor/bin/coveralls -v
