language: php

php:
    - 7.1

install:
    - composer install
    - composer database:migrate

script:
    - composer run test:unit
    - composer run test:integration
    - composer run test:feature
